include $(MODULE_SECURE_SHELL)/ssh-client.mk
include $(MODULE_SECURE_SHELL)/ssh-agent.mk
include $(MODULE_SECURE_SHELL)/ssh-github.mk
include $(MODULE_SECURE_SHELL)/doc.mk
include $(MODULE_SECURE_SHELL)/config.cfg
